# YAML build pipeline for a simple PHP web app on Windows

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'PHP'
  buildConfiguration: 'Release'

steps:


- script: |
    choco install -y php
  displayName: 'Install PHP'

- script: |
    php -v
  displayName: 'Verify PHP Installation'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Archive Source Files'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'drop'
    pathToPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
  displayName: 'Publish Artifact'
